name: Scrape & Upload Card Price

on:
  schedule:
    - cron: '*/30 * * * *'      # every 30 minutes
  workflow_dispatch:           # manual trigger

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    env:
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_KEY:     ${{ secrets.AZURE_STORAGE_KEY }}
      CARD_NAME:             "Iono"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install scraper dependencies
        run: npm install --prefer-offline --no-audit --progress=false

      - name: Run Puppeteer scraper
        run: node scraper.js
